# Generated by Django 4.2.16 on 2024-11-27 13:41

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0004_groupchat_is_private_groupchat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
