# Generated by Django 4.2.16 on 2024-11-28 08:50

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0007_groupchat_admin_groupchat_group_chat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='group_avatar',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
