# Generated by Django 4.2.16 on 2024-12-20 08:55

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0008_groupchat_group_avatar_alter_groupchat_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
